using PgfPlotsSdk.Public.Interfaces.Builders.FluentPgfPlot.Capabilities;

namespace PgfPlotsSdk.Public.Interfaces.Builders.FluentPgfPlot.Composed;

public interface ICanAddWrapperOrAddRoot: 
	ICanAddWrapper<ICanAddAxisContents<ICanAddAxisContentsOrSetAxisOptionsOrBuild>, ICanAddPieContents<ICanAddPieContentsOrSetPieOptionsOrBuild>>,
	ICanAddRoot<ICanAddWrapperOrAddWrapperDecorationsOrSetWrapperOptions> { }